model:
  type: wresnet28_10
dataset: svhn
aug: d
genotype: k1_cifar10_test
cutout: 20
batch: 512
epoch: 200
lr: 0.02
lr_schedule:
  type: 'cosine'
  warmup:
    multiplier: 4
    epoch: 5
optimizer:
  type: sgd
  nesterov: True
  decay: 0.001
