model:
  type: wresnet28_10
dataset: cifar100
aug: d
genotype: k1_cifar10_test
cutout: 16
batch: 128
epoch: 200
lr: 0.1
lr_schedule:
  type: 'cosine'
  warmup:
    multiplier: 4
    epoch: 5
optimizer:
  type: sgd
  nesterov: True
  decay: 0.0005
